name: Deploy to Oracle compute instance

on:
  push:
    branches:
      - master
    type:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/news-traveler-server
          tmux kill-session -t newsTraveler
          tmux new-session -d -s newsTraveler
          tmux send-keys -t newsTraveler 'git pull origin master' C-m
          tmux send-keys -t newsTraveler 'python3 -m poetry install --no-root --no-interaction' C-m
          tmux send-keys -t newsTraveler 'source .venv/bin/activate' C-m
          tmux send-keys -t newsTraveler 'python3 -m flask run --host=0.0.0.0' C-m

          